'use client';

import { motion } from 'framer-motion';
import { Wallet, TrendingUp, Download, FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { toast } from 'sonner';
import { PageHeader } from '@/components/page-header';
import { StatCard } from '@/components/stat-card';
import { SectionCard } from '@/components/section-card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/components/auth-provider';
import { getStudentKey, studentFees, studentFeeSummary, studentProfiles } from '@/lib/student-data';
import { ExportButtons } from '@/components/export-buttons';
import type { ExportColumn } from '@/lib/export-utils';

export default function StudentFeesPage() {
  const { profile } = useAuth();
  const key = getStudentKey(profile?.email?.split('@')[0]);
  const fees = studentFees[key];
  const summary = studentFeeSummary[key];
  const student = studentProfiles[key];

  const exportColumns: ExportColumn[] = [
    { key: 'feeType', label: 'Fee Type' }, { key: 'amount', label: 'Amount' }, { key: 'paidAmount', label: 'Paid' },
    { key: 'status', label: 'Status' }, { key: 'dueDate', label: 'Due Date' }, { key: 'paymentDate', label: 'Payment Date' },
  ];

  const handleDownloadReceipt = (feeType: string, receiptNo: string, paymentDate: string | null, method: string | null) => {
    if (!student) return;

    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 42;

    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, pageWidth, 78, 'F');

    doc.setFillColor(255, 255, 255);
    doc.circle(52, 39, 20, 'F');
    doc.setTextColor(79, 70, 229);
    doc.setFont('helvetica', 'bold');
    doc.text('YS', 44, 43);

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('Yovial School', 84, 31);
    doc.setFont('helvetica', 'normal');
    doc.text('CBSE Affiliated • Bengaluru', 84, 49);

    doc.setTextColor(17, 24, 39);
    doc.setFont('helvetica', 'bold');
    doc.text('Fee Payment Receipt', margin, 110);
    doc.setFont('helvetica', 'normal');
    doc.text('Professional receipt generated for the student fee payment record.', margin, 128);

    doc.setDrawColor(217, 221, 226);
    doc.roundedRect(margin, 142, pageWidth - margin * 2, 270, 12, 12, 'S');

    const rows = [
      ['Receipt Number', receiptNo],
      ['Student Name', student.name],
      ['Admission Number', student.admissionNumber],
      ['Class & Section', `${student.classGrade}-${student.section}`],
      ['Fee Type', feeType],
      ['Amount Paid', `₹${fees.find((item) => item.receiptNo === receiptNo)?.paidAmount.toLocaleString('en-IN') ?? '0'}`],
      ['Payment Date', paymentDate ?? '—'],
      ['Payment Mode', method ?? '—'],
      ['Transaction ID', receiptNo],
      ['Status', 'PAID'],
    ];

    rows.forEach((row, index) => {
      const y = 172 + index * 22;
      doc.setFillColor(index % 2 === 0 ? 248 : 255, 250, 252);
      doc.rect(margin + 8, y - 14, pageWidth - margin * 2 - 16, 20, 'F');
      doc.setTextColor(107, 114, 128);
      doc.setFont('helvetica', 'bold');
      doc.text(row[0], margin + 16, y);
      doc.setTextColor(17, 24, 39);
      doc.setFont('helvetica', 'normal');
      doc.text(row[1], margin + 170, y);
    });

    doc.setTextColor(17, 24, 39);
    doc.setFont('helvetica', 'bold');
    doc.text('Authorized Signature', margin, 445);
    doc.setDrawColor(79, 70, 229);
    doc.line(margin + 122, 440, pageWidth - margin, 440);
    doc.setTextColor(107, 114, 128);
    doc.setFont('helvetica', 'normal');
    doc.text('Principal / Accounts Office', margin + 150, 447);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Confidential • Generated by Yovial School ERP', margin, 475);

    doc.save(`Receipt_${receiptNo}.pdf`);
    toast.success('Receipt downloaded', { description: `${receiptNo} — ${feeType}` });
  };

  return (
    <div className="space-y-6">
      <PageHeader title="Fees" description="Your fee history and payment status">
        <ExportButtons label="fees" data={fees as unknown as Record<string, unknown>[]} columns={exportColumns} filename="my-fees" />
      </PageHeader>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard title="Total Due" value={`₹${summary.totalDue.toLocaleString('en-IN')}`} icon={Wallet} delay={0} />
        <StatCard title="Total Paid" value={`₹${summary.totalPaid.toLocaleString('en-IN')}`} icon={TrendingUp} changeType="positive" delay={0.05} />
        <StatCard title="Pending" value={`₹${summary.pending.toLocaleString('en-IN')}`} icon={Wallet} changeType="negative" delay={0.1} />
        <StatCard title="Status" value={summary.status} icon={Wallet} changeType={summary.status === 'Up to date' ? 'positive' : summary.status === 'Partial payment' ? 'neutral' : 'negative'} delay={0.15} />
      </div>

      <SectionCard title="Fee History" description={`${fees.length} fee records`} delay={0.2}>
        <div className="overflow-x-auto rounded-xl border">
          <table className="w-full">
            <thead><tr className="border-b bg-muted/30 text-left text-xs font-medium text-muted-foreground"><th className="px-4 py-3">Fee Type</th><th className="px-4 py-3 text-right">Amount</th><th className="px-4 py-3 text-right">Paid</th><th className="px-4 py-3">Due Date</th><th className="px-4 py-3">Payment Date</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Receipt</th></tr></thead>
            <tbody>
              {fees.map((fee, i) => (
                <motion.tr key={fee.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: i * 0.03 }} className="border-b text-sm last:border-0">
                  <td className="px-4 py-3 font-medium">{fee.feeType}</td>
                  <td className="px-4 py-3 text-right">₹{fee.amount.toLocaleString('en-IN')}</td>
                  <td className="px-4 py-3 text-right">{fee.paidAmount > 0 ? `₹${fee.paidAmount.toLocaleString('en-IN')}` : '—'}</td>
                  <td className="px-4 py-3 text-muted-foreground">{fee.dueDate}</td>
                  <td className="px-4 py-3 text-muted-foreground">{fee.paymentDate ?? '—'}</td>
                  <td className="px-4 py-3"><Badge variant="secondary" className={`capitalize ${fee.status === 'paid' ? 'bg-success/10 text-success' : fee.status === 'partial' ? 'bg-accent/10 text-accent' : fee.status === 'overdue' ? 'bg-destructive/10 text-destructive' : 'bg-muted text-muted-foreground'}`}>{fee.status}</Badge></td>
                  <td className="px-4 py-3 text-right">{fee.receiptNo ? <Button size="sm" variant="ghost" className="h-8 gap-1.5" onClick={() => handleDownloadReceipt(fee.feeType, fee.receiptNo!, fee.paymentDate, fee.method)}><Download className="h-3.5 w-3.5" />{fee.receiptNo}</Button> : <span className="text-xs text-muted-foreground">—</span>}</td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
      </SectionCard>

      {summary.pending > 0 && (
        <SectionCard title="Payment Due" description="You have pending fee payments" delay={0.3}>
          <div className="flex flex-col items-center gap-4 py-6 text-center">
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-destructive/10"><FileText className="h-7 w-7 text-destructive" /></div>
            <div>
              <p className="text-lg font-bold text-destructive">₹{summary.pending.toLocaleString('en-IN')} pending</p>
              <p className="mt-1 text-sm text-muted-foreground">Please clear your dues at the accounts office or through online payment.</p>
            </div>
            <Button className="gap-2" onClick={() => toast.info('Online payment portal coming soon')}>Pay Now</Button>
          </div>
        </SectionCard>
      )}
    </div>
  );
}
